### ISSUE TITLE
Crash when trying to log in with wrong password

### ISSUE THREAD

**Issue by LeonGeorgi** [ascii-dresden/ascii-pay-frontend#12]
![image](https://user-images.githubusercontent.com/10584088/134770616-8d65c20d-4bed-4b58-ac9f-6eaae683f3a2.png)

**Comment by pibebtol** [comment]
Ich würde an der Stelle dann einfach mal verbieten, dass man das falsche Passwort eingeben kann.
Oder keine Passwort Authentifizierung ;)
